import { Tool } from "../types";

export const categories = [
  "All",
  "3D Rendering",
  "Floor Planning",
  "Interior Design",
  "Mood Boards",
  "Site Planning",
  "Sustainability",
  "Generative Design",
  "Visualization",
  "Documentation",
];

export const pricingTypes = ["All", "Free", "Freemium", "Paid", "Enterprise"];

// Tool of the Week
export const toolOfTheWeek: Tool = {
  id: 0,
  name: "Veras (by Chaos)",
  description: "A BIM-native AI plugin that transforms 3D geometry from Revit and SketchUp into photorealistic renders using diffusion models.",
  category: "3D Rendering",
  pricing: "Paid",
  rating: 4.9,
  features: ["Revit Integration", "SketchUp Support", "Diffusion Models"],
  website: "evolvelab.io/veras",
  featured: true,
};

// Free tools (visible to all users)
export const freeTools: Tool[] = [
  {
    id: 1,
    name: "Veras (by Chaos)",
    description: "A BIM-native AI plugin that transforms 3D geometry from Revit and SketchUp into photorealistic renders using diffusion models.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.9,
    features: ["Revit Integration", "SketchUp Support", "Diffusion Models"],
    website: "evolvelab.io/veras",
    featured: true,
  },
  {
    id: 2,
    name: "Autodesk Forma",
    description: "An AI-driven conceptual design tool that provides real-time analysis for wind, noise, and sun hours during early site planning.",
    category: "Site Planning",
    pricing: "Paid",
    rating: 4.8,
    features: ["Wind Analysis", "Sun Hours", "Noise Mapping"],
    website: "autodesk.com/forma",
    featured: true,
  },
  {
    id: 3,
    name: "Midjourney",
    description: "The industry standard for high-fidelity conceptual ideation, atmosphere generation, and complex material exploration.",
    category: "Mood Boards",
    pricing: "Paid",
    rating: 4.9,
    features: ["Conceptual Ideation", "Material Exploration", "Atmosphere Generation"],
    website: "midjourney.com",
    featured: true,
  },
  {
    id: 4,
    name: "Rendair AI",
    description: "Built specifically for architects to turn rough sketches or white-card models into professional visualizations instantly.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.6,
    features: ["Sketch to Render", "White-card Models", "Instant Visualization"],
    website: "rendair.ai",
  },
  {
    id: 5,
    name: "Ark Design AI",
    description: "An AI platform that generates optimized schematic floor plans based on specific spatial requirements and local building codes.",
    category: "Floor Planning",
    pricing: "Paid",
    rating: 4.7,
    features: ["Code Compliance", "Spatial Optimization", "Schematic Plans"],
    website: "ark.land",
  },
  {
    id: 6,
    name: "Interior AI",
    description: "A rapid visualization tool that allows users to upload a photo and restyle a room across 30+ different interior design aesthetics.",
    category: "Interior Design",
    pricing: "Freemium",
    rating: 4.5,
    features: ["30+ Aesthetics", "Photo Upload", "Rapid Visualization"],
    website: "interiorai.com",
  },
  {
    id: 7,
    name: "LookX",
    description: "An AI-trained rendering engine developed specifically for architectural logic, ensuring structural elements are interpreted correctly.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.7,
    features: ["Architectural Logic", "Structural Recognition", "AI Rendering"],
    website: "lookx.ai",
  },
  {
    id: 8,
    name: "TestFit",
    description: "A feasibility and generative design tool that automates site plans, parking layouts, and building massing for developers.",
    category: "Floor Planning",
    pricing: "Enterprise",
    rating: 4.8,
    features: ["Site Automation", "Parking Layouts", "Building Massing"],
    website: "testfit.io",
    featured: true,
  },
  {
    id: 9,
    name: "Spacely AI",
    description: "A professional-grade tool for interior designers to create furniture layouts and 4K renders from simple floor plan uploads.",
    category: "Interior Design",
    pricing: "Paid",
    rating: 4.6,
    features: ["4K Renders", "Furniture Layouts", "Floor Plan Upload"],
    website: "spacely.ai",
  },
  {
    id: 10,
    name: "Maket.ai",
    description: "Uses generative AI to produce thousands of floor plan variations and architectural concepts from text-based project briefs.",
    category: "Floor Planning",
    pricing: "Paid",
    rating: 4.5,
    features: ["Text-to-Plan", "1000+ Variations", "Concept Generation"],
    website: "maket.ai",
  },
  {
    id: 11,
    name: "Planner 5D",
    description: "A hybrid tool that uses AI to convert 2D blueprints into interactive 3D models with automated furniture arrangement features.",
    category: "Floor Planning",
    pricing: "Freemium",
    rating: 4.4,
    features: ["2D to 3D", "Auto Furniture", "Interactive Models"],
    website: "planner5d.com",
  },
  {
    id: 12,
    name: "Adobe Firefly",
    description: "Integrated into Photoshop, it allows designers to extend renders, swap materials, and generate textures via generative fill.",
    category: "Mood Boards",
    pricing: "Paid",
    rating: 4.8,
    features: ["Photoshop Integration", "Generative Fill", "Material Swap"],
    website: "adobe.com/firefly",
    featured: true,
  },
  {
    id: 13,
    name: "Kaedim",
    description: "A specialized tool that converts 2D sketches and elevation drawings into textured 3D meshes for use in Rhino or Blender.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.5,
    features: ["2D to 3D Mesh", "Rhino Support", "Blender Export"],
    website: "kaedim3d.com",
  },
  {
    id: 14,
    name: "Archicad AI Visualizer",
    description: "A native Graphisoft tool that creates generative design previews directly within the BIM environment to bridge concept to detail.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.6,
    features: ["BIM Native", "Graphisoft", "Generative Previews"],
    website: "graphisoft.com",
  },
  {
    id: 15,
    name: "Homestyler",
    description: "A cloud-based design tool featuring an AI 'Decorate' function that suggests furniture and finishes from real-world brands.",
    category: "Interior Design",
    pricing: "Freemium",
    rating: 4.3,
    features: ["AI Decorate", "Real Brands", "Cloud-Based"],
    website: "homestyler.com",
  },
  {
    id: 16,
    name: "KREA AI",
    description: "A real-time image enhancement and upscaling tool that refines architectural sketches into high-definition visuals as you draw.",
    category: "Mood Boards",
    pricing: "Paid",
    rating: 4.7,
    features: ["Real-time Enhancement", "Upscaling", "Sketch Refinement"],
    website: "krea.ai",
  },
  {
    id: 17,
    name: "Arko AI",
    description: "An AI assistant for Rhino and Revit that applies high-quality textures and lighting to 'clay' models in seconds.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.6,
    features: ["Rhino Plugin", "Revit Plugin", "Clay to Real"],
    website: "arko.ai",
  },
  {
    id: 18,
    name: "Finch 3D",
    description: "A generative tool that uses graph technology to optimize floor plans for efficiency, ensuring compliance with spatial constraints.",
    category: "Floor Planning",
    pricing: "Paid",
    rating: 4.7,
    features: ["Graph Technology", "Efficiency Optimization", "Constraint Solving"],
    website: "finch3d.com",
  },
  {
    id: 19,
    name: "ARCHITEChTURES",
    description: "An AI-powered residential design platform that automates building layouts while tracking real-time cost and area data.",
    category: "Floor Planning",
    pricing: "Enterprise",
    rating: 4.5,
    features: ["Residential Focus", "Cost Tracking", "Area Analysis"],
    website: "architechtures.com",
  },
  {
    id: 20,
    name: "Cove.tool",
    description: "An AI analysis engine that helps architects optimize building performance, including daylighting, carbon, and energy costs.",
    category: "Sustainability",
    pricing: "Paid",
    rating: 4.8,
    features: ["Daylight Analysis", "Carbon Tracking", "Energy Optimization"],
    website: "cove.tools",
    featured: true,
  },
];

// Premium tools (only visible to subscribers)
export const premiumTools: Tool[] = [
  {
    id: 101,
    name: "Hypar Generative",
    description: "A cloud-based generative design platform that creates thousands of design variants using parametric constraints and AI optimization.",
    category: "Generative Design",
    pricing: "Enterprise",
    rating: 4.9,
    features: ["Parametric Design", "Cloud Computing", "API Integration"],
    website: "hypar.com",
    featured: true,
    isNew: true,
  },
  {
    id: 102,
    name: "Delve by Sidewalk Labs",
    description: "Google's AI-powered tool for real estate developers that generates optimal building configurations from site constraints.",
    category: "Site Planning",
    pricing: "Enterprise",
    rating: 4.8,
    features: ["Google AI", "Real Estate Optimization", "Site Analysis"],
    website: "sidewalklabs.com/delve",
    isNew: true,
  },
  {
    id: 103,
    name: "Spacemaker (Autodesk)",
    description: "AI-driven site planning tool that maximizes buildable area while analyzing environmental factors like wind, noise, and daylight.",
    category: "Site Planning",
    pricing: "Enterprise",
    rating: 4.9,
    features: ["Environmental Analysis", "Maximize Buildable Area", "Autodesk Ecosystem"],
    website: "autodesk.com/spacemaker",
    featured: true,
  },
  {
    id: 104,
    name: "Archistar",
    description: "An Australian AI platform that combines site feasibility, 3D massing, and real-time compliance checking in one interface.",
    category: "Site Planning",
    pricing: "Enterprise",
    rating: 4.7,
    features: ["Feasibility Analysis", "Compliance Checking", "3D Massing"],
    website: "archistar.ai",
  },
  {
    id: 105,
    name: "Coohom AI",
    description: "A lightning-fast interior visualization tool that generates photorealistic renders from floor plans in under 10 seconds.",
    category: "Interior Design",
    pricing: "Paid",
    rating: 4.6,
    features: ["10-Second Renders", "Floor Plan Import", "Furniture Library"],
    website: "coohom.com",
  },
  {
    id: 106,
    name: "PromeAI",
    description: "A versatile AI rendering tool that transforms sketches, models, and text prompts into stunning architectural visualizations.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.5,
    features: ["Multi-Input Rendering", "Text-to-Image", "Style Transfer"],
    website: "prome.ai",
  },
  {
    id: 107,
    name: "Mirage AI",
    description: "A high-end rendering solution for Archicad and Revit that uses AI to create cinematic-quality visualizations automatically.",
    category: "3D Rendering",
    pricing: "Enterprise",
    rating: 4.8,
    features: ["Cinematic Quality", "BIM Integration", "Automated Lighting"],
    website: "mirage-ai.com",
    featured: true,
  },
  {
    id: 108,
    name: "Vizcom AI",
    description: "Real-time rendering tool that converts 3D model viewpoints into hand-drawn artistic styles as you navigate through your model.",
    category: "Visualization",
    pricing: "Paid",
    rating: 4.7,
    features: ["Real-time Rendering", "Artistic Styles", "3D Navigation"],
    website: "vizcom.ai",
  },
  {
    id: 109,
    name: "ArcGIS CityEngine",
    description: "AI-powered procedural modeling for urban planning that generates entire city blocks from planning rules and constraints.",
    category: "Site Planning",
    pricing: "Enterprise",
    rating: 4.6,
    features: ["Procedural Modeling", "Urban Planning", "GIS Integration"],
    website: "esri.com/cityengine",
  },
  {
    id: 110,
    name: "Swapp AI",
    description: "An AI construction documentation platform that automates the creation of detailed drawings from BIM models.",
    category: "Documentation",
    pricing: "Enterprise",
    rating: 4.5,
    features: ["Auto Documentation", "BIM to Drawings", "Construction Docs"],
    website: "swapp.ai",
  },
  {
    id: 111,
    name: "D5 Render AI",
    description: "Real-time rendering with AI-powered scene population, automatic lighting, and instant material assignment.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.8,
    features: ["Real-time Rendering", "AI Scene Population", "Auto Materials"],
    website: "d5render.com",
    featured: true,
  },
  {
    id: 112,
    name: "Enscape 4.0 AI",
    description: "The latest version with AI-assisted asset placement, automatic scene optimization, and voice-controlled rendering.",
    category: "Visualization",
    pricing: "Paid",
    rating: 4.7,
    features: ["Voice Control", "AI Asset Placement", "Scene Optimization"],
    website: "enscape3d.com",
  },
  {
    id: 113,
    name: "Luma AI View",
    description: "NeRF-based 3D capture tool that creates editable architectural models from smartphone video scans of existing spaces.",
    category: "3D Rendering",
    pricing: "Paid",
    rating: 4.6,
    features: ["NeRF Technology", "Video to 3D", "Smartphone Capture"],
    website: "lumalabs.ai",
    isNew: true,
  },
  {
    id: 114,
    name: "Giraffe by AutoDesSys",
    description: "AI-powered organic modeling for creating complex curved surfaces and parametric architectural forms.",
    category: "Generative Design",
    pricing: "Paid",
    rating: 4.4,
    features: ["Organic Modeling", "Parametric Forms", "Curved Surfaces"],
    website: "autodes.com/giraffe",
  },
  {
    id: 115,
    name: "Twinmotion AI",
    description: "Epic Games' real-time visualization tool with AI-powered scene assembly, pathfinding, and crowd simulation.",
    category: "Visualization",
    pricing: "Paid",
    rating: 4.8,
    features: ["Unreal Engine", "Crowd Simulation", "Pathfinding AI"],
    website: "twinmotion.com",
    featured: true,
  },
];